### ISSUE TITLE
Very nice work! And have you considered the Kernel Correction in the original Polyblur report? 

### ISSUE THREAD

**Issue by zsbluesky** [teboli/polyblur#7]

**Comment by teboli** [comment]
Dear zsbluesky, do you mean the non-blind deblurring part of the algorithm? In that case yes I reimplemented both the Gaussian blur estimator and the approximate inverse filter in this repo. These separate components may be found in respectively the polyblur/blur_estimation.py and polyblur/deblurring.py files.
